version: '3.8'
services:
  node_api:
    build: ./node_api
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    depends_on:
      - python_ai

  python_ai:
    build: ./python_ai
    ports:
      - "8000:8000"
    env_file:
      - ../.env
