FROM python:3.12

WORKDIR /usr/src/app
COPY ./python_ai/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ./python_ai .

EXPOSE 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
